import vtk
import pandas as pd

def build_point_weights(vtk_ungrid, points):
    pointWeights = vtk.vtkDoubleArray()
    pointWeights.SetName("PointWeight")
    pointWeights.SetNumberOfComponents(1)
    pointWeights.SetNumberOfTuples(vtk_ungrid.GetNumberOfPoints())

    points.apply(lambda x: pointWeights.SetTuple1(int(x[0]), x[4]), axis = 1)
    return pointWeights

def build_weights(vtk_ungrid, cells, name):
    cellWeights = vtk.vtkDoubleArray()
    cellWeights.SetName(name)
    cellWeights.SetNumberOfComponents(1)
    cellWeights.SetNumberOfTuples(vtk_ungrid.GetNumberOfCells())
    cells.apply(lambda x: cellWeights.SetTuple1(int(x[0]), x[1]), axis = 1)
    return cellWeights

def init_points(vtk_pts, points):
    points.apply(lambda x: vtk_pts.InsertPoint(int(x[0]), x[1], x[2], x[3]), axis = 1)

def build_line(points):
    line = vtk.vtkLine()
    line.GetPointIds().SetId(0, int(points[0]))
    line.GetPointIds().SetId(1, int(points[1]))
    return line

def init_lines(vtk_cells, lines):
    """
    return a table with 2 columns {Cell ID (generated by vtk), Weight (read in input)}
    """
    return lines.apply(lambda x: pd.Series({"ID": vtk_cells.InsertNextCell(build_line(x)), "Weight": x[2]}), axis = 1)

def build_cell(x):
    cell = vtk.vtkTriangle()
    Ids = cell.GetPointIds()
    Ids.SetId(0,int(x[0]))
    Ids.SetId(1,int(x[1]))
    Ids.SetId(2,int(x[2]))
    return cell

def init_faces(vtk_cells, faces):
    """
    return a table with 2 columns {Cell ID (generated by vtk), Weight (read in input)}
    """
    return faces.apply(lambda x: pd.Series({"ID": vtk_cells.InsertNextCell(build_cell(x)), "Weight": x[3]}), axis = 1)

def build_tetra(x):
    tetra = vtk.vtkTetra()
    Ids = tetra.GetPointIds()
    Ids.SetId(0, int(x[0]))
    Ids.SetId(1, int(x[1]))
    Ids.SetId(2, int(x[2]))
    Ids.SetId(3, int(x[3]))
    return tetra


def init_tetras(vtk_cells, tetras):
    """
    return a table with 2 columns {Cell ID (generated by vtk), Weight (read in input)}
    """
    return tetras.apply(lambda x: pd.Series({"ID": vtk_cells.InsertNextCell(build_tetra(x)), "Weight": x[4]}), axis = 1)

def get_vtypes(weights, types):
    vtypes = vtk.vtkUnsignedCharArray()
    vtypes.SetNumberOfComponents(1)
    nb_cells = sum([df.shape[0] for df in weights])
    vtypes.SetNumberOfTuples(nb_cells)
    for i in range(len(weights)):
        df = weights[i]
        tpe = types[i]
        df.apply(lambda x: vtypes.SetTuple1(int(x[0]), tpe), axis = 1)
    return vtypes

def build_vectors(vtk_ungrid_glyph, vectors_dir):
    vectors = vtk.vtkDoubleArray()
    vectors.SetName("Vector Field")
    vectors.SetNumberOfComponents(3)
    vectors.SetNumberOfTuples(vtk_ungrid_glyph.GetNumberOfPoints())
    vectors_dir.apply(lambda x: vectors.SetTuple3(x[0],x[1], x[2], x[3]), axis = 1)
    vtk_ungrid_glyph.GetPointData().AddArray(vectors)
    vtk_ungrid_glyph.GetPointData().SetActiveVectors("Vector Field")

def build_mesh(faces, points, lines, tetras, output_file='format/generated_vtp/output.vtu'):
    vtk_ungrid = vtk.vtkUnstructuredGrid()

    vtk_pts = vtk.vtkPoints()
    vtk_cells = vtk.vtkCellArray()

    init_points(vtk_pts, points)

    lines_weight = init_lines(vtk_cells, lines)
    weights = [lines_weight]
    types = [vtk.VTK_LINE]

    if not faces.empty:
        faces_weight = init_faces(vtk_cells, faces)
        weights.append(faces_weight)
        types.append(vtk.VTK_TRIANGLE)

    if not tetras.empty:
        tetras_weight = init_tetras(vtk_cells, tetras)
        weights.append(tetras_weight)
        types.append(vtk.VTK_TETRA)

    vtypes = get_vtypes(weights=weights, types=types)

    vtk_ungrid.SetPoints(vtk_pts)
    vtk_ungrid.SetCells(vtypes, vtk_cells)

    lines_weight = lines_weight.set_index("ID").reindex(range(vtk_ungrid.GetNumberOfCells()), fill_value=float("nan")).reset_index()

    if not faces.empty:
        faces_weight = faces_weight.set_index("ID").reindex(range(vtk_ungrid.GetNumberOfCells()), fill_value=float("nan")).reset_index()
    if not tetras.empty:
        tetras_weight = tetras_weight.set_index("ID").reindex(range(vtk_ungrid.GetNumberOfCells()), fill_value=float("nan")).reset_index()

    vtk_pts_weight = build_point_weights(vtk_ungrid, points)
    vtk_ungrid.GetPointData().SetScalars(vtk_pts_weight)
    vtk_ungrid.GetPointData().SetActiveScalars("PointWeight")

    vtk_lines_weight = build_weights(vtk_ungrid, lines_weight, "LineWeight")
    vtk_ungrid.GetCellData().AddArray(vtk_lines_weight)

    if not faces.empty:
        vtk_faces_weight = build_weights(vtk_ungrid, faces_weight, "FacesWeight")
        vtk_ungrid.GetCellData().AddArray(vtk_faces_weight)

    if not tetras.empty:
        vtk_tetras_weight = build_weights(vtk_ungrid, tetras_weight, "TetrasWeight")
        vtk_ungrid.GetCellData().AddArray(vtk_tetras_weight)

    writer = vtk.vtkXMLUnstructuredGridWriter()
    writer.SetFileName(output_file)
    writer.SetInputData(vtk_ungrid)

    writer.Write()

def build_glyph(vectors_pts, vectors_dir):
    vtk_ungrid_glyph = vtk.vtkUnstructuredGrid()
    vtk_vec_pts = vtk.vtkPoints()

    init_points(vtk_vec_pts, vectors_pts)
    vtk_ungrid_glyph.SetPoints(vtk_vec_pts)

    build_vectors(vtk_ungrid_glyph, vectors_dir)
    arrow_source = vtk.vtkArrowSource()

    add_arrows = vtk.vtkGlyph3D()
    add_arrows.SetInputData(vtk_ungrid_glyph)
    add_arrows.SetSourceConnection(arrow_source.GetOutputPort())
    add_arrows.Update()

    writer = vtk.vtkXMLUnstructuredGridWriter()
    writer.SetInputConnection(add_arrows.GetOutputPort())
    writer.SetFileName('output2.vtu')
    writer.SetInputData(vtk_ungrid_glyph)

    writer.Write()

def main(paths):
    points = pd.read_csv(paths["points"])
    lines = pd.read_csv(paths["lines"])

    faces = pd.DataFrame([])
    if "triangles" in paths:
        faces = pd.read_csv(paths["triangles"])

    tetras = pd.DataFrame([])
    if "tetras" in paths:
        tetras = pd.read_csv(paths["tetras"])

    build_mesh(faces, points, lines, tetras, paths["output"])

    if "vectors" in paths and "vectors_dir" in paths:
        vectors_pts = pd.read_csv(paths["vectors"])
        vectors_dir = pd.read_csv(paths["vectors_dir"])

        build_glyph(vectors_pts, vectors_dir)

if __name__ == "__main__":
    paths = {
        "points" : "csv_files/graph_points.csv",
        "lines" : "csv_files/graph_lines.csv",
        "triangles" : "csv_files/graph_triangles.csv",
        "tetras" : "csv_files/tetra.csv",
        "vectors" : "csv_files/vectors.csv",
        "vectors_dir" : "csv_files/vectors_dir.csv"
    }
    main(paths)
